repo: "use-all-the-selectors"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    search:
      - "background-color: #fdf6e3;"
      - "font-size: 1.5rem;"
      - "font-family: sans-serif;"
      - "text-transform: uppercase;"
      - "background-color: #eee8d5;"
      - "color: #93a1a1;"
      - "background-color: #b58900;"
      - "color: #fff;"
      - "background-color: #719e07;"
      - "background-color: #2694d8;"
      - "color: #719e47;"
      - "color: #2aa198;"
      - "background-color: #657ba3;"
      - "background-color: #586e75;"
      - "background-color: #d04b16;"

screenshots:
  - path: 'index.html'
    sizes: [608]
